name: Rust

on:
  push:
    banches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Install rlottie
        run: |
          wget -q "https://github.com/Samsung/rlottie/archive/refs/tags/v$pkgver.tar.gz"
          tar xfz v$pkgver.tar.gz
          cd rlottie-$pkgver
          wget -q "https://aur.archlinux.org/cgit/aur.git/plain/0001-add-missing-include.patch?h=rlottie" -o 0001-add-missing-include.patch
          patch --forward --strip=0 --input=0001-add-missing-include.patch
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DCMAKE_BUILD_TYPE=Release
          make -j2
          sudo make install
          cd ../..
      - run: cargo test --workspace
  
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
  
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Install rlottie
        run: |
          wget -q "https://github.com/Samsung/rlottie/archive/refs/tags/v$pkgver.tar.gz"
          tar xfz v$pkgver.tar.gz
          cd rlottie-$pkgver
          wget -q "https://aur.archlinux.org/cgit/aur.git/plain/0001-add-missing-include.patch?h=rlottie" -o 0001-add-missing-include.patch
          patch --forward --strip=0 --input=0001-add-missing-include.patch
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DCMAKE_BUILD_TYPE=Release
          make -j2
          sudo make install
          cd ../..
      - run: cargo doc --workspace --no-deps
        env:
          RUSTDOCFLAGS: "--default-theme ayu"
      - run: tar c target/doc/ | zstd -10 -o rustdoc.tar.zst
      - uses: actions/upload-artifact@v2
        with:
          name: rustdoc
          path: rustdoc.tar.zst
  
  pages:
    runs-on: ubuntu-latest
    needs: [doc]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: actions/download-artifact@v2
        with:
          name: rustdoc
      - run: |
          tar xfa rustdoc.tar.zst --strip-components=1
          rm rustdoc.tar.zst
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "GitHub Pages for ${{github.sha}}"
